[tool.poetry]
name = "juptest"
version = "0.1.0"
description = ""
authors = ["3hx <code@3hx.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jupyter = "^1.0.0"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
